### ISSUE TITLE
URISyntaxException thrown when invalid URL was encountered in OpenTelemetryTracer

### ISSUE THREAD

**Issue by sebastianhaeni** [eclipse-vertx/vertx-tracing#74]
### Version

io.vertx:vertx-opentelemetry:4.3.4

### Context

When a request is made to the service with an unusual URL, an exception is thrown originating by tracing, because the URL cannot be parsed and added as a tag to the span. 

Tag extraction should not throw exceptions based on non-standard URLs.

```
java.net.URISyntaxException: Illegal character in query at index 56: /wp-admin/admin-post.php?swp_debug=load_options&swp_url=<pre>system('cat
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at i.v.core.http.impl.HttpUtils.absoluteURI(HttpUtils.java:481)
	at i.v.c.h.i.Http1xServerRequest.absoluteURI(Http1xServerRequest.java:377)
	at i.v.core.http.impl.HttpUtils$1.value(HttpUtils.java:88)
	at i.v.core.http.impl.HttpUtils$1.value(HttpUtils.java:69)
	at i.v.t.o.OpenTelemetryTracer.reportTagsAndStart(OpenTelemetryTracer.java:151)
	at i.v.t.o.OpenTelemetryTracer.receiveRequest(OpenTelemetryTracer.java:65)
	at i.v.t.o.OpenTelemetryTracer.receiveRequest(OpenTelemetryTracer.java:31)
	at i.v.c.h.i.Http1xServerRequest.reportRequestBegin(Http1xServerRequest.java:600)
	at i.v.c.h.i.Http1xServerRequest.handleBegin(Http1xServerRequest.java:157)
	at i.v.c.h.i.Http1xServerConnection.handleMessage(Http1xServerConnection.java:143)
	at i.v.c.net.impl.ConnectionBase.read(ConnectionBase.java:157)
	at i.v.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
```

### Do you have a reproducer?

Example URL: `/wp-admin/admin-post.php?swp_debug=load_options&swp_url=<pre>system('cat`

### Steps to reproduce

1. Instrument application with vertx-opentelemetry
2. Make a request with the above URL
3. URISyntaxException exception gets thrown

**Comment by tsegismont** [comment]
Thanks for the report

**Comment by tsegismont** [comment]
For clarification, the `URISyntaxException` is logged by `Http1xServerRequest#absoluteURI`, which returns a `null` value in this case. Tags data is still extracted and, for OpenTelemetry, the absolute URL is not a required attribute.

An issue related to the `absoluteUri` method has already been filed to Vert.x core: https://github.com/eclipse-vertx/vert.x/issues/2797

Before it is fixed and to avoid polluting logs, you can change the log level of `io.vertx.core.http.impl.Http1xServerRequest`.

**Comment by tsegismont** [comment]
Fixed by https://github.com/eclipse-vertx/vert.x/pull/5158
