### ISSUE TITLE
Compatibility with Zipkin Reporter 3.3 (or 3.4) and Zipkin 6 (and Spring Boot 3)

### ISSUE THREAD

**Issue by jensbaitingerbosch** [eclipse-vertx/vertx-tracing#80]
#### Describe the feature

Vertx tracing should use (or be compatible with Zipkin 6)

#### Use cases

The main use case are applicitions using Spring Boot 3.x and Vert.x. Spring Boot 3.x comes with Zipkin 6 and the zipkin reporter 3.3. Combining these versions with vertx tracing throws the following Exception:

```
Caused by: java.lang.AbstractMethodError: Receiver class io.vertx.tracing.zipkin.VertxSender does not define or inherit an implementation of the resolved method 'abstract zipkin2.reporter.Encoding encoding()' of interface zipkin2.reporter.BytesMessageSender.
	at zipkin2.reporter.AsyncReporter$Builder.<init>(AsyncReporter.java:95)
	at zipkin2.reporter.AsyncReporter.builder(AsyncReporter.java:55)
	at zipkin2.reporter.AsyncReporter.builder(AsyncReporter.java:50)
	at io.vertx.tracing.zipkin.ZipkinTracingOptions.buildTracer(ZipkinTracingOptions.java:168)
	at io.vertx.tracing.zipkin.ZipkinTracerFactory.tracer(ZipkinTracerFactory.java:61)
	at io.vertx.tracing.zipkin.ZipkinTracerFactory.tracer(ZipkinTracerFactory.java:20)
	at io.vertx.core.spi.VertxTracerFactory.init(VertxTracerFactory.java:36)
	at io.vertx.core.impl.VertxBuilder.initProviders(VertxBuilder.java:284)
	at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:275)
	at io.vertx.core.Vertx$1.internalBuilder(Vertx.java:122)
	at io.vertx.core.Vertx$1.build(Vertx.java:126)
	at io.vertx.core.Vertx.vertx(Vertx.java:151)
	at io.vertx.junit5.VertxParameterProvider.newInstance(VertxParameterProvider.java:68)
	at io.vertx.junit5.VertxParameterProvider.newInstance(VertxParameterProvider.java:38)
	at io.vertx.junit5.VertxExtension.lambda$resolveParameter$0(VertxExtension.java:105)
	at io.vertx.junit5.VertxExtension.resolveParameter(VertxExtension.java:104)
```

#### Contribution

I am currently clarifying the process, if my company can contribute this, though it should be not a big issue upgrading the dependency and adopting some calls

**Comment by tsegismont** [comment]
It would be fine to upgrade it in Vert.x 5. Yes please, send a PR if you can

**Comment by vietj** [comment]
it would be great to have a contribution @jensbaitingerbosch for this upgrade

**Comment by tsegismont** [comment]
Fixed by #87
